# Generated by Django 3.0.7 on 2022-05-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_end_year',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_start_year',
            field=models.TextField(),
        ),
    ]
